ifeq ($(__BUILDING_FOR_ARM__),1)
  $(info building for arm)
else ifeq ($(__BUILDING_FOR_X86__),1)
  $(info building for x86)
endif


EXAMPLE4_SUBDIR1_KOBJ = example4-subdir1-kmod
obj-m += $(EXAMPLE4_SUBDIR1_KOBJ).o
$(EXAMPLE4_SUBDIR1_KOBJ)-objs := example4-subdir1.o
